<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

In [1]:
import numpy as np

# Might as well just do it now

In [ ]:
# I'll make the examples for this entire topic about storing data about pokemon if it is ok with you whoever is reading this :p

In [ ]:
# Context: Pokemon are names of the creature. Types are like the elements of the creature.

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

In [3]:
#Python Lists

py_pokemon = ["Charmander", "Bulbasaur", "Squirtle"]
py_type = ["Fire", "Grass", "Water"]


In [11]:
#Numpy arrays 
np_pokemon = np.array(["Charmander", "Bulbasaur", "Squirtle"])
np_type = np.array(["Fire", "Grass", "Water"])

In [5]:
#Dictionary 

pokemon_data = {
    "Charmander": "Fire",
    "Bulbasaur" : "Grass",
    "Squirtle" : "Water" 
}

## 1.2 Accessing data from a list (or array)

In [13]:
#From list 

py_pokemon = ["Charmander", "Bulbasaur", "Squirtle"]
py_type = ["Fire", "Grass", "Water"]

# Indexing starts from zero!!

print(py_pokemon[0])
print(py_type[2])

Charmander
Water


In [14]:
# Using negative index to count from back of list
# Last element is [-1]
# We need to know the size of the list to work

print(py_pokemon[-1])
print(py_type[-2])

Squirtle
Grass


In [16]:
# Example with array

np_pokemon = np.array(["Charmander", "Bulbasaur", "Squirtle"])
np_type = np.array(["Fire", "Grass", "Water"])

print(np_pokemon[0])
print(np_pokemon[-3])

Charmander
Charmander


## 1.3 Accessing data from a dictionary

In [19]:
# Dictionary 
# Using keys to access values (format of dictionary --> keys : values)

pokemon_data = {
    "Pikachu": "Electric",
    "Psyduck" : "Water",
    "Eevee" : "Normal" 
}

print(pokemon_data["Pikachu"])

Electric


In [20]:
# Show all keys in dict
pokemon_data.keys()

dict_keys(['Pikachu', 'Psyduck', 'Eevee'])

In [21]:
# Show all values in dict
pokemon_data.values()

dict_values(['Electric', 'Water', 'Normal'])

## 1.4 Higher dimensional lists

In [22]:
# Example of a 2D list or array

pokemon_info = [
    ['Pikachu','Electric'],
    ['Eevee','Normal'],
    ['Psyduck','Water']
]

np_pokeinfo = np.array(pokemon_info)

np_pokeinfo

array([['Pikachu', 'Electric'],
       ['Eevee', 'Normal'],
       ['Psyduck', 'Water']], dtype='<U8')

# 2 Lists vs. Arrays

## 2.1 Size

In [26]:
pokemon_info_2d =  [
 ['Pikachu','Electric'], ['Charmander','Fire'],
    ['Eevee','Normal'], ['Squirtle','Water'],
    ['Psyduck','Water'], ['Bulbasaur','Grass']   
]

# For lists, to find out size,

len(pokemon_info_2d)

6

In [29]:
np_pokeinfo2d = np.array(pokemon_info_2d)

# For arrays, to find out size,

print(len(np_pokeinfo2d))
print(np_pokeinfo2d.shape)

# Note: Shape is not a function, but an attribute of the numpy array.

6
(6, 2)


## 2.2 Arrays are fussy about type

In [31]:
py_list = [1,2.5,'Pikachu']
np_array = np.array(py_list)

py_list

[1, 2.5, 'Pikachu']

In [32]:
np_array

# Notice the dtype = <U32 and how the numbers are converted to str
# Anw we can easily typecast using .astype()

array(['1', '2.5', 'Pikachu'], dtype='<U32')

## 2.3 Adding a number

In [34]:
number_list = [1,2,3,4,5]
np_array = np.array(number_list)

py_list + 10     # This will NOT work!!
                 # TypeError: can only concatenate list (not "int") to list

TypeError: can only concatenate list (not "int") to list

In [35]:
np_array + 10 

# This Will Work, output = array([11, 12, 13, 14, 15])

array([11, 12, 13, 14, 15])

## 2.4 Adding another list

In [37]:
number_list1 = [1,2,3,4,5]
number_list2 = [10,20,30,40,50]
np_array1 = np.array(number_list1)
np_array2 = np.array(number_list2)

number_list1 + number_list2   

# This will work! Ref to error msg for previous example (concatenate list to list)
# But its just connecting two lists together

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [38]:
np_array1 + np_array2

# This also works, but its an arimethric addition of both elements at the same index

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [39]:
number_list = [1,2,3,4,5]
np_array = np.array(number_list)

number_list * 2

# Will work, but this just makes the list grow.

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [40]:
np_array * 2

# Now this multiplies every element in the array by the number

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [41]:
number_list = [2,4,6,8,10]
np_array = np.array(number_list)

py_list**2 

# This will NOT work!
# TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [42]:
np_array ** 2

# Now this works! All elements in the array are raised to the power of 2

array([  4,  16,  36,  64, 100])

## 2.7 Asking questions

In [43]:
number_list = [2,4,6,8,10]
np_array = np.array(number_list)

In [47]:
number_list == 2

# This is meaningless. I think its saying that number_list (list format) == 2 is false

False

In [49]:
number_list > 3

# Will not work
#TypeError: '>' not supported between instances of 'list' and 'int'

TypeError: '>' not supported between instances of 'list' and 'int'

In [52]:
np_array == 6

# Will work as now we are comparing equality between the elements and the value

array([False, False,  True, False, False])

In [51]:
np_array > 3

# Will also work

array([False,  True,  True,  True,  True])

## 2.8 Mathematics

In [53]:
number_list = [2,4,6,8,10]
np_array = np.array(number_list)

In [59]:
print(sum(number_list))
print(sum(np_array))
print(np_array.sum())

# Both works fine in summation
# Note: For all examples below too, number_list.sum() will NOT work

30
30
30


In [60]:
print(max(number_list))
print(max(np_array))
print(np_array.max())

#Both works fine in giving me maximum value

10
10
10


In [61]:
print(min(number_list))
print(min(np_array))
print(np_array.min())

#Both works fine in giving me minimum value

2
2
2


In [63]:
print(np_array.mean())
print(np_array.std())

#Additional math stats functions for array

6.0
2.8284271247461903


# Exercises & Self-Assessment

In [79]:
# Isnt the exercises supposed to be in the next notebook?
# I guess I'll just do some random stuff here

pokemon_data = {                  # Just a pokemon dictionary
    "Charmander": "1",
    "Bulbasaur" : "2",
    "Squirtle" : "3", 
    "Eevee" : "4",
    "Pikachu" : "5"
}

len(pokemon_data)                 # 5 sets of key-value pair in the dictionary


names = list(pokemon_data.keys())         # Converted the keys (pokemon name) into a list
number = list(pokemon_data.values())      # Converted the values (identifier) into a list

array_names = np.array(names)
array_number = np.array(number)

array_names == "Charmander"              # Is Charmander in the list?
                                         # output: array([ True, False, False, False, False])

math = array_number.astype(float)               # converting these numbers into float for some math

print(math.sum())
print(math**4)
print(math.std())

15.0
[  1.  16.  81. 256. 625.]
1.4142135623730951


## Footnotes