<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

Essential summary:
- Subsetting means to ‘select’ in general (ie produce a subset).
- Indexing refers to selecting one element (just ONE element).
- Slicing refers to selecting a range of elements (multiple elements).

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [4]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# using lists

x = py_list

print(x[1])         # Indexing
print(x[1:5])       # Slicing
print(x[::])
print(x[4:])

b2
['b2', 'c3', 'd4', 'e5']
['a1', 'b2', 'c3', 'd4', 'e5', 'f6', 'g7', 'h8', 'i9', 'j10']
['e5', 'f6', 'g7', 'h8', 'i9', 'j10']


In [10]:
# Using arrays

x = np_array

print(x[-2])
print(x[0:8:3])   # Index 0 to 8 in steps of 3
print(x[::-2])    # Reverse the list in steps of 2

i9
['a1' 'd4' 'g7']
['j10' 'h8' 'f6' 'd4' 'b2']


## 1.2 Arrays only | Subsetting by masking

In [11]:
# ONLY with numpy arrays
# Create a mask

np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array < 7
my_mask

# Answer to the question is in the form of yes no, and is stored in the my_mask variable

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False])

In [13]:
# Now show me the elements in the mask
# 'Overlay' the yes no answers ontop of the array to give me the 'yes' values

np_array[my_mask]

array([1, 2, 3, 4, 5, 6])

In [14]:
#Otherwise a more elegant method is simply

np_array[np_array > 5]

array([ 6,  7,  8,  9, 10])

In [16]:
# Now invert the mask

np_array[~(np_array > 5)]

array([1, 2, 3, 4, 5])

In [21]:
# Now use the boolean operator AND

np_array[(np_array > 5) & (np_array < 9)]

array([6, 7, 8])

In [23]:
# Now use the boolean operator OR

np_array[(np_array > 5) | (np_array < 2)]

array([ 1,  6,  7,  8,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [36]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

print(py_list_2d[0])
print(py_list_2d[-5])
print(py_list_2d[1][1])
print(py_list_2d[:2])
print(np_array_2d[-3,0])
print(np_array_2d[:2,1])
print(py_list_2d[:2][1])   # HMMMMMMMM, this just gives me the second of the list of py_list_2d[:2]

[1, 'A']
[6, 'F']
B
[[1, 'A'], [2, 'B']]
8
['A' 'B']
[2, 'B']


## 1.4 Growing lists

In [37]:
#Creating a larger list from a smaller one

x = [1,2]*5
x  # This simply result in 5 of the original list combined

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [42]:
# Appending elements

x = [1]
x = x + [2]
x = x + [3]
x = x + [10]

y = [2]
y += [3]
y += [122]
y += [10000]


z = []                   #initialise empty list. I love this next trick
for i in range(0,10):
    z.append(i)

print(x)
print(y)
print(z) 

[1, 2, 3, 10]
[2, 3, 122, 10000]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [43]:
# Differences between .extend and .append

x = [1,2,3]
x += [11,22,33]

y = [1,2,3]
y.extend([10,20,30])

z = [4,6,8]
z.append([1,2,3])

print(x)
print(y)
print(z) 

[1, 2, 3, 11, 22, 33]
[1, 2, 3, 10, 20, 30]
[4, 6, 8, [1, 2, 3]]


# Some loose ends

## 1.5 Tuples

In [45]:
a = (2,4,6)     #Define tuple. This is a tuple

# We can access data
print(a[0])

# but we cannot modify data

a[0] += 1       #TypeError: 'tuple' object does not support item assignment

2


TypeError: 'tuple' object does not support item assignment

In [49]:
#But we can do this!

a = ('hello' , 10)
name, number = a

number += 1

print(number)

11


## 1.6 Be VERY careful when copying

In [26]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

# Just dont try anything funny with immutable objects
# If im not wrong any edits to y and z will affect x too

[1, 2, 3]

In [ ]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

# Exercises & Self-Assessment

In [74]:
# Exercises in exercise folder
# This is just a practise ground for me


# Find me all the pokemon with the type "electric"

pokemon = [['pikachu', "electric"], ['charmander', "fire"], 
           ['squirtle', "water"], ['zekrom', "electric"],
           ['voltorb', "electric"], ["manectric", "electric"]]

array = np.array(pokemon)

mask = array[:6,1] == 'electric'

array[:,[0]][mask]  

array([['pikachu'],
       ['zekrom'],
       ['voltorb'],
       ['manectric']], dtype='<U10')

## Footnotes